PREFIX=/usr/local/lemberg

LIBLLSYMS=__divdf3,__divsf3,__divdi3,__divsi3,__moddi3,__modsi3,__udivdi3,__udivsi3,__umoddi3,__umodsi3,__ashldi3,__ashrdi3,__lshrdi3,__muldi3,memset,memmove,memcpy

LLVM_LD=llvm-ld -b $@ $^ \
	${PREFIX}/lib/libllsyms.o ${LLVM_LDFLAGS} \
	-L ${PREFIX}/lib -lc -lm -llemberg -lnosys -lll \
	-internalize-public-api-list=${LIBLLSYMS},main

%.bc : %.c
	llvm-gcc -U__i386__ -D__lemberg__ ${CFLAGS} --emit-llvm -c -I ${PREFIX}/include -o $@ $<

%.opt.bc : %.linked.bc
	opt -disable-simplify-libcalls ${OPTFLAGS} -o $@ $<

%.s : %.opt.bc
	llc -march=lemberg ${LLCFLAGS} -o $@ $<

%.dat : %.s
	${PREFIX}/bin/as -d -o $@ ${PREFIX}/lib/crt0.s $^ ${PREFIX}/lib/crtend0.s

%.bin : %.s
	${PREFIX}/bin/as -b -o $@ ${PREFIX}/lib/crt0.s $^ ${PREFIX}/lib/crtend0.s
