PREFIX=/usr/local/lemberg

CC=clang -target lemberg 
ARCH=
CPPFLAGS=-I ${PREFIX}/include

AS=${PREFIX}/bin/as
LD=${PREFIX}/bin/ld
OBJCOPY=${PREFIX}/bin/objcopy

%.bc : %.c
	${CC} ${ARCH} -c -emit-llvm ${CPPFLAGS} ${CFLAGS} -o $@ $^

%.s : %.c
	${CC} ${ARCH} -S ${CPPFLAGS} ${CFLAGS} -o $@ $^

%.o : %.c
	${CC} ${ARCH} -c ${CPPFLAGS} ${CFLAGS} -o $@ $^

%.o : %.s
	${CC} ${ARCH} -c ${ASFLAGS} -o $@ $^

%.elf : %.o
	${CC} ${ARCH} ${LDFLAGS} -o $@ $^ ${LDLIBS}

%.dat : %.elf
	${OBJCOPY} -d -o $@ $<

%.bin : %.elf
	${OBJCOPY} -b -o $@ $<
